In [173]:
print("hello world")

hello world


In [174]:
import pandas as pd
import numpy as np


In [175]:


# Read CSV file
df = pd.read_csv("train.csv")

# See first few rows
print(df.head())


   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD   

In [176]:
data = df.select_dtypes(include=['number']).to_numpy()


In [191]:
np.shape(data)
y = data[:,37]
print(y)

In [181]:
y.shape


(1460,)

In [182]:
x = data[:,:-1]
x.shape

(1460, 37)

In [196]:
from sklearn.impute import SimpleImputer



# Impute missing values with column means
imputer = SimpleImputer(strategy="mean")
x = imputer.fit_transform(data)

# Separate features and target
y = x[:, -1]   # assuming last column is SalePrice
x = x[:, :-1]

print("Any NaN left in x?", np.isnan(x).any())
print("Any NaN left in y?", np.isnan(y).any())


Any NaN left in x? False
Any NaN left in y? False


In [205]:
n = x.shape[1]
init_w = np.full((n,),0.8)
init_b = 0.8

37


In [204]:
print(init_w.shape)
print(x)
print(np.isnan(x).any())   # True if NaNs in features
print(np.isnan(y).any())   # True if NaNs in target



(37,)
[[1.000e+00 6.000e+01 6.500e+01 ... 0.000e+00 2.000e+00 2.008e+03]
 [2.000e+00 2.000e+01 8.000e+01 ... 0.000e+00 5.000e+00 2.007e+03]
 [3.000e+00 6.000e+01 6.800e+01 ... 0.000e+00 9.000e+00 2.008e+03]
 ...
 [1.458e+03 7.000e+01 6.600e+01 ... 2.500e+03 5.000e+00 2.010e+03]
 [1.459e+03 2.000e+01 6.800e+01 ... 0.000e+00 4.000e+00 2.010e+03]
 [1.460e+03 2.000e+01 7.500e+01 ... 0.000e+00 6.000e+00 2.008e+03]]
False
False


In [206]:

m = len(x)
print(m)
y_pred = np.zeros(m)
def predict(X, w, b):
    return np.dot(X, w) + b
            


1460


In [208]:
def calc_cost(actual,prediction):
    c=0
    cost = 0
    for i in range(m):
        c+= (actual[i] - prediction[i])**2
    cost = (1/(2*m))*c
    return cost

In [209]:
y_pred = predict(x, init_w, init_b)

print(y)
print(y_pred)

J = calc_cost(y, y_pred)

[208500. 181500. 223500. ... 266500. 142125. 147500.]
[18050.4 18783.2 20524.8 ... 22696.8 19381.6 20424.8]


Formula for Gradient:

djdw = 1/m sum(((wx_i + b) - yi)xi)
djdb = 1/m sum(((wx_i + b) - yi ))

In [ ]:
def gradient(w,b):
    
    for i in range(m):
        dw = 