In [1]:
print("hello world")

hello world


In [4]:
import pandas as pd
import numpy as np


In [5]:


# Read CSV file
df = pd.read_csv("train.csv")

# See first few rows
print(df.head())


   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD   

In [96]:
data = df.select_dtypes(include=['number']).to_numpy()


In [97]:
np.shape(data)

(1460, 38)

In [99]:
print(data[:,37])

[208500. 181500. 223500. ... 266500. 142125. 147500.]


In [101]:
y = data[:,37]

In [102]:
print(y)

[208500. 181500. 223500. ... 266500. 142125. 147500.]


In [103]:
y.shape


(1460,)

In [164]:
init_w = 1
init_b = 0.8

In [165]:
x = data[:]
x.shape

(1460, 38)

In [166]:
print(x[:,1])

[60. 20. 60. ... 70. 20. 20.]


In [171]:
def preditct():
    m = len(x)
    y_pred = np.zeros(m)

    for i in range(m):
        for j in range(36):
            y_pred[i] += init_w * x[i][j] + init_b

In [ ]:
def calculate_cost():
    